### ISSUE TITLE
Export der Zeiten in "Chef-fähiges" Format

### ISSUE THREAD

**Issue by BenStee** [StormyCode/TimeLogger#16]
Wäre cool, wenn man die gespeicherten Zeiten in einer besser lesbaren Form exportieren könnte, die man auch zur Not dem Chef vorlegen kann (Excel / PDF / ...).
Im "logfile"-Bereich gibt es zwar einen "Speichern"-Button, der funktioniert allerdings nicht.

**Comment by StormyCode** [comment]
Das "Nicht-Funktionieren" des <kbd>Speichern</kbd> Buttons wurde schon in Issue #15 festgehalten und mit dem [July Patch](https://github.com/StormyCode/TimeLogger/releases) behoben.
Bezüglich des Export Formats: Der <kbd>Speichern</kbd> Buttons speichert die Log-Zeiten als ```.csv``` Datei. Diese ist von Excel lesbar. Von dort aus kann sich dann ```.pdf``` oder ```.xslx``` Dateien generieren lassen.
